### ISSUE TITLE
Improve deck tracker in-game performance

### ISSUE THREAD

**Issue by extesy** [extesy/DeckTracker#21]
Try to profile and take a look how it can be made faster. Ideas:
- [x] Switch to Unity event loop. This would fix all random intermittent game bugs.
- [x] Don't use network within logger's Update() function.
- [x] Don't stream event messages at all unless in a debug mode.
- [x] Cache background textures when drawing overlay.
- [x] Investigate if caching localization data makes sense.
- [x] Lower priority of spawned threads.

**Comment by extesy** [comment]
Should be a little better in `1.0.60`.

**Comment by extesy** [comment]
@VitaliyKulikov please check if the performance is better in `1.0.62`.

**Comment by extesy** [comment]
@VitaliyKulikov please check if the performance is better in `1.0.62`.

**Comment by VitaliyKulikov** [comment]
@extesy same. maybe, freezes are slower. before, sometimes some freezes was for 3-5 secs. now, 1-2 .. but it's initial observation for patch `1.0.62`

**Comment by extesy** [comment]
I will keep investigating, but your report is the only one so far and in a few streams I watched I don't see it, for example https://www.twitch.tv/techandjunk

**Comment by VitaliyKulikov** [comment]
he also have freeses. it's just less noticeable now. in any case, now is better then `1.0.61`

**Comment by extesy** [comment]
@VitaliyKulikov Try `1.0.63`, it should be twice faster at drawing overlay according to my metrics.

**Comment by extesy** [comment]
@VitaliyKulikov Try `1.0.64`, it should be twice faster at drawing overlay according to my metrics.

**Comment by extesy** [comment]
@VitaliyKulikov Try `1.0.65`, it should be twice faster at drawing overlay according to my metrics.

**Comment by VitaliyKulikov** [comment]
@extesy it's better) good job. now, micro-freezes not appears rapidly. but, time-by-time - once/twice in 5 mins (3-4 per game) it happens.  it don't have common nature, can be just during some animation or even without any action by user.

**Comment by extesy** [comment]
And there are no such micro-freezes without the tracker running? Like not even a single one?

**Comment by VitaliyKulikov** [comment]
with `tracker` even on mega-low video-graphic quality micro-freezes happens.
without `tracker` game runs smoothly ((.

**Comment by vanish2k** [comment]
Thnx for improvements! After last update 0.67 i have nearly always 60 fps ingame, while before it was dropping to ~35 during tracker activity.

**Comment by bender8k** [comment]
help! can`t run
Error
Something went wrong
the object reference does not point to an instance of the object(ссылка на объект  не указывает на экземпляр  объекта)

**Comment by SithLordOfSnark** [comment]
I get that error too whenever I try to load it. Hope there's a fix.

**Comment by Darkvamper** [comment]
I use this tool in conjunction with TES Legends, and while it's very useful, whilst in a pvp-game I will get random screen-freezing for a few seconds. This happens quite often (about every other turn).
This occurs almost always when a rune is being broken. I do have a fairly low spec system (2.5 GHtz, terrible graphics card, 12G RAM). Are there certain scripts I can disable to improve performance, without affecting functionality too much (I don't use the opponent's played cards tracker for example).

**Comment by gliese58i** [comment]
The deck tracker doesn't seem to work at all with the latest TESL Morrowind expansion.
Starting the game with the deck tracker running displays the message "You have been disconnected due to an error" then closes the game down. The same happens if you start the deck tracker after the game is already running.

**Comment by Siegfreid** [comment]
Hello everyone,

I'm actually having an issue with deck tracker, I followed the instructions of the tutorial here : https://github.com/extesy/DeckTracker and I installed the windows runtime package, because I wasn't able to neither export my collection or import a deck. After the installation, the sentence "Running game detected : the elder scrolls legend" is now green ! :grinning: 
But, it doesn't show my deck list, and I already tried to lauch the program before TESL. So I'm running out of ideas. I'm sorry if the answer has already been given but I checked all the topics before and no one seems to answers to my problem. 
I attach an image of the window of deck tracker (it's blank but who knows) : https://www.noelshack.com/2018-17-2-1524567422-reporting-issue-deck-tracker.png

If there is any answer you need to know to help, ask me I'll try to answer (but I'm not an expert in soft/hardwares :)

**Comment by demek12345** [comment]
Will the deck tracker work with the new game client ?
